# Generated by Django 5.2.4 on 2025-08-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="firstname",
        ),
        migrations.RemoveField(
            model_name="student",
            name="lastname",
        ),
        migrations.AddField(
            model_name="student",
            name="gpa",
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="name",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="rollno",
            field=models.CharField(default=None, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="semester",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
