# Generated by Django 5.2.4 on 2025-08-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_remove_student_firstname_remove_student_lastname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="department",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
