# Generated by Django 5.2.4 on 2025-08-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_student_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="gpa",
            field=models.FloatField(default=0.0),
        ),
    ]
